### ISSUE TITLE
Problem text too dark

### ISSUE THREAD

**Issue by GaPhilippone** [Jeffser/Jeffser.github.io#3]
Hello, just a little problem with the blog, the text is really too dark and impossible to read:
![image](https://github.com/user-attachments/assets/aa82184f-8c4f-4131-badd-527b8924ca41)

**Comment by Jeffser** [comment]
yeah yeah I haven't updated this in a long time and never checked if it worked properly on every browser, will probably remake the website from 0 when I finish my current period on College
